/* AUTO-GENERATED by determinism_test --generate.
 *
 * 100 reference IEEE-754 bit patterns for terrain(n, e), one
 * per input in determinism_test.c's make_input() index space.
 * Indices 0..49 are HASH-EXACT (bit-equality required across
 * platforms). Indices 50..99 are FBM-DRIFT (ULP-tolerant).
 *
 * To regenerate (after an intentional change to the shared math):
 *   cmake -S src/terrain -B src/terrain/build-native
 *   cmake --build src/terrain/build-native
 *   ./src/terrain/build-native/determinism_test --generate \
 *       > tests/terrain/determinism_reference.h
 */

#ifndef HAWKEYE_TESTS_TERRAIN_DETERMINISM_REFERENCE_H_
#define HAWKEYE_TESTS_TERRAIN_DETERMINISM_REFERENCE_H_

#include <stdint.h>

static const uint32_t DETERMINISM_REFERENCE_BITS[100] = {
	0x3f85a0c4u,  /* [  0] hash  -> 1.04396868 */
	0xbefc4334u,  /* [  1] hash  -> -0.492700219 */
	0xbf08a812u,  /* [  2] hash  -> -0.533814549 */
	0x3f915f5du,  /* [  3] hash  -> 1.13572276 */
	0x3dcd44f0u,  /* [  4] hash  -> 0.100229144 */
	0x3f28c6d2u,  /* [  5] hash  -> 0.659283757 */
	0xbee8fc5cu,  /* [  6] hash  -> -0.455050349 */
	0xbeb28ae0u,  /* [  7] hash  -> -0.348715782 */
	0x3edcf060u,  /* [  8] hash  -> 0.431521416 */
	0x3f844ec1u,  /* [  9] hash  -> 1.03365338 */
	0x3fbc1c7bu,  /* [ 10] hash  -> 1.46961915 */
	0xbf79f72cu,  /* [ 11] hash  -> -0.976427794 */
	0x3ed3ff48u,  /* [ 12] hash  -> 0.414057016 */
	0x3f362bd2u,  /* [ 13] hash  -> 0.711606145 */
	0xbec50ab8u,  /* [ 14] hash  -> -0.384847403 */
	0xbe5406d0u,  /* [ 15] hash  -> -0.207057238 */
	0xbec6c71cu,  /* [ 16] hash  -> -0.388237834 */
	0xbfe1accfu,  /* [ 17] hash  -> -1.7630862 */
	0xbd833780u,  /* [ 18] hash  -> -0.0640707016 */
	0x3ebe1efcu,  /* [ 19] hash  -> 0.371330142 */
	0xbf6c7cc0u,  /* [ 20] hash  -> -0.923778534 */
	0xbf23e35eu,  /* [ 21] hash  -> -0.640188098 */
	0xbe91c324u,  /* [ 22] hash  -> -0.28469193 */
	0x3e328ca8u,  /* [ 23] hash  -> 0.174364686 */
	0x3f6496c4u,  /* [ 24] hash  -> 0.892925501 */
	0xbf0bf28au,  /* [ 25] hash  -> -0.546669602 */
	0x3fca0195u,  /* [ 26] hash  -> 1.57817328 */
	0xbe117ff0u,  /* [ 27] hash  -> -0.142089605 */
	0x3f7d6b5au,  /* [ 28] hash  -> 0.989919305 */
	0x3fc9608bu,  /* [ 29] hash  -> 1.57325876 */
	0xbcb96e00u,  /* [ 30] hash  -> -0.0226354599 */
	0x3fbab291u,  /* [ 31] hash  -> 1.45857441 */
	0x3f074784u,  /* [ 32] hash  -> 0.528434992 */
	0xbf939d8fu,  /* [ 33] hash  -> -1.15324581 */
	0xbe95b938u,  /* [ 34] hash  -> -0.292428732 */
	0x3e8e4640u,  /* [ 35] hash  -> 0.277879715 */
	0x3f284c64u,  /* [ 36] hash  -> 0.657415628 */
	0x3c2dcf00u,  /* [ 37] hash  -> 0.0106084347 */
	0x3ea3a17cu,  /* [ 38] hash  -> 0.319591403 */
	0x3ef4f058u,  /* [ 39] hash  -> 0.478396177 */
	0x3e9c4ba4u,  /* [ 40] hash  -> 0.305264592 */
	0xbe6f0bf8u,  /* [ 41] hash  -> -0.233444095 */
	0x3f81123cu,  /* [ 42] hash  -> 1.00836897 */
	0xbfc60248u,  /* [ 43] hash  -> -1.54694462 */
	0xbe03e798u,  /* [ 44] hash  -> -0.128813148 */
	0xbf8ac48eu,  /* [ 45] hash  -> -1.08412337 */
	0xbdaf86d0u,  /* [ 46] hash  -> -0.0857063532 */
	0x3fb1d160u,  /* [ 47] hash  -> 1.38920212 */
	0xbf4ace58u,  /* [ 48] hash  -> -0.792211056 */
	0x3fc635cfu,  /* [ 49] hash  -> 1.54851711 */
	0xc0db008cu,  /* [ 50] fbm   -> -6.84381676 */
	0x413808e2u,  /* [ 51] fbm   -> 11.5021687 */
	0x40b7091au,  /* [ 52] fbm   -> 5.71986103 */
	0xc0462554u,  /* [ 53] fbm   -> -3.09602833 */
	0x3f59c8c6u,  /* [ 54] fbm   -> 0.85071981 */
	0xc1399fc8u,  /* [ 55] fbm   -> -11.6015091 */
	0x4144ea99u,  /* [ 56] fbm   -> 12.3072748 */
	0x41026c2cu,  /* [ 57] fbm   -> 8.15140915 */
	0x3fa9fd70u,  /* [ 58] fbm   -> 1.3280468 */
	0x40a0af8bu,  /* [ 59] fbm   -> 5.02142859 */
	0xc026d914u,  /* [ 60] fbm   -> -2.6069994 */
	0xbeed6730u,  /* [ 61] fbm   -> -0.463677883 */
	0xc1038952u,  /* [ 62] fbm   -> -8.22102547 */
	0xbc06da00u,  /* [ 63] fbm   -> -0.00823068619 */
	0x4002d8a4u,  /* [ 64] fbm   -> 2.04447269 */
	0xc1a0af23u,  /* [ 65] fbm   -> -20.085516 */
	0xbfd3cc5fu,  /* [ 66] fbm   -> -1.65467441 */
	0x40cd1408u,  /* [ 67] fbm   -> 6.40869522 */
	0xc089875cu,  /* [ 68] fbm   -> -4.29777336 */
	0x40066988u,  /* [ 69] fbm   -> 2.10019112 */
	0xbf3716f4u,  /* [ 70] fbm   -> -0.715193987 */
	0xc0aff237u,  /* [ 71] fbm   -> -5.49831724 */
	0x40e5fb56u,  /* [ 72] fbm   -> 7.18693066 */
	0x40044d22u,  /* [ 73] fbm   -> 2.06720781 */
	0x3eed33d0u,  /* [ 74] fbm   -> 0.463285923 */
	0xbf143538u,  /* [ 75] fbm   -> -0.578937054 */
	0x410a6836u,  /* [ 76] fbm   -> 8.65044212 */
	0x400bf012u,  /* [ 77] fbm   -> 2.18652773 */
	0x3f99d5c9u,  /* [ 78] fbm   -> 1.20183671 */
	0xbfe52c9du,  /* [ 79] fbm   -> -1.79042399 */
	0xc1533519u,  /* [ 80] fbm   -> -13.2004633 */
	0x4040752au,  /* [ 81] fbm   -> 3.00715113 */
	0x3f7d52beu,  /* [ 82] fbm   -> 0.989543796 */
	0x4019a5b4u,  /* [ 83] fbm   -> 2.40073872 */
	0xc016393fu,  /* [ 84] fbm   -> -2.34724402 */
	0x3c9fac00u,  /* [ 85] fbm   -> 0.0194911957 */
	0x3fc0ec1du,  /* [ 86] fbm   -> 1.50720561 */
	0x4045d41cu,  /* [ 87] fbm   -> 3.09107113 */
	0x40868770u,  /* [ 88] fbm   -> 4.2040329 */
	0xc0812135u,  /* [ 89] fbm   -> -4.03530359 */
	0xbd8779a0u,  /* [ 90] fbm   -> -0.06614995 */
	0x40b6919bu,  /* [ 91] fbm   -> 5.70527411 */
	0x40bf593cu,  /* [ 92] fbm   -> 5.97964287 */
	0xc133e5ccu,  /* [ 93] fbm   -> -11.2436028 */
	0x3ef07682u,  /* [ 94] fbm   -> 0.469654143 */
	0xbf1058f8u,  /* [ 95] fbm   -> -0.563857555 */
	0x414a5950u,  /* [ 96] fbm   -> 12.6468048 */
	0xc120efffu,  /* [ 97] fbm   -> -10.0585928 */
	0xbf8ad348u,  /* [ 98] fbm   -> -1.08457279 */
	0xbe132000u,  /* [ 99] fbm   -> -0.143676758 */
};

#endif /* HAWKEYE_TESTS_TERRAIN_DETERMINISM_REFERENCE_H_ */
